# Generated by Django 5.2.7 on 2025-10-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0005_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tumbnail',
            new_name='thumbnail',
        ),
    ]
