# Generated by Django 5.2.7 on 2025-10-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0006_rename_tumbnail_course_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='instructorApp.course')),
                ('user_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='instructorApp.course')),
            ],
        ),
    ]
