# Generated by Django 5.2.7 on 2025-10-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0009_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='course_instace',
            new_name='course_instance',
        ),
    ]
